#!/usr/bin/bash

#function use
show(){
 local name="$1"
 echo "Hello $name"
 }
 show "$1"
 show "$2"
 show "$3"

 sum(){
 num1=50
 num2=50
 result=$(($num1 + $num2))
 echo "Your team result is: $result"
 }
 sum

 list(){
  local name="$@"
  echo "$name !! Eagle Eyes"
}
list "$@"